const color = {
  text: '#606060',
  primary: '#007c4d',
  secondary: '#b900ed',
  contrast: '#191919',
  error: '#E53535',
  error1: 'rgba(225, 55, 55, .5)',
  success: 'rgba(65, 175, 70, .1)',
  errorContrast: '#ffcdd5',
  disabled: '#B5B5B5',
  grey1: '#353745',
  grey2: '#47495c',
  grey3: '#595B73',
  grey4: '#6A6D8A',
  grey5: '#80839D',
  grey6: '#979AAF',
  grey7: '#AEB0C1',
  green1: '#DAD7CD',
  green2: '#BFC4AC',
  green3: '#A3B18A',
  green4: '#588157',
  green5: '#496E4C',
  green6: '#3A5A40',
  green7: '#344E41',
  background: '#ffffff',
};

const gradient = {
  gradientPrimary: `linear-gradient(135deg, ${color.primary} 0%, ${color.primary} 100%)`,
  gradientSecondary: `linear-gradient(135deg, ${color.primary} 0%, ${color.secondary} 100%)`,
};

const shadow = {
  content: {
    hOffset: 0,
    vOffset: 3,
    blur: 7,
    spread: 0,
    color: 'rgba(45, 40, 60, 0.3)',
  },
  simple: {
    hOffset: 0,
    vOffset: 3,
    blur: 4,
    spread: 0,
    color: 'rgba(125, 130, 145, 0.1)',
  },
  none: {
    hOffset: 0,
    vOffset: 0,
    blur: 0,
    spread: 0,
    color: 'rgba(38, 40, 56, 0.12)',
  },
};

const size = {
  xs: 4,
  s: 8,
  sm: 12,
  m: 16,
  ml: 20,
  l: 24,
  xl: 32,
  xxl: 36,
};

const animationTime = {
  slow: 0.6,
  normal: 0.3,
  fast: 0.1,
};

const typography = {
  h: {
    fontFamily: 'nunito-bold, sans-serif',
    fontFamilyBold: 'nunito-bold, sans-serif',
    fontSize: 72,
    lineHeight: 108,
  },
  h1: {
    fontFamily: 'aileron-bold, sans-serif',
    fontFamilyBold: 'nunito-bold, sans-serif',
    fontSize: 56,
    lineHeight: 84,
  },
  h2: {
    fontFamily: 'nunito-bold, sans-serif',
    fontFamilyBold: 'nunito-bold, sans-serif',
    fontSize: 40,
    lineHeight: 60,
  },
  h3: {
    fontFamily: 'nunito-bold, sans-serif',
    fontFamilyBold: 'nunito-bold, sans-serif',
    fontSize: 32,
    lineHeight: 48,
  },
  h4: {
    fontFamily: 'nunito-semi-bold, sans-serif',
    fontFamilyBold: 'nunito-bold, sans-serif',
    fontSize: 24,
    lineHeight: 36,
  },
  h5: {
    fontFamily: 'nunito-semi-bold, sans-serif',
    fontFamilyBold: 'nunito-bold, sans-serif',
    fontSize: 20,
    lineHeight: 32,
  },
  h6: {
    fontFamily: 'nunito-semi-bold, sans-serif',
    fontFamilyBold: 'nunito-bold, sans-serif',
    fontSize: 16,
    lineHeight: 24,
  },
  h7: {
    fontFamily: 'nunito-semi-bold, sans-serif',
    fontFamilyBold: 'nunito-bold, sans-serif',
    fontSize: 14,
    lineHeight: 20,
  },
  h8: {
    fontFamily: 'nunito-semi-bold, sans-serif',
    fontFamilyBold: 'nunito-bold, sans-serif',
    fontSize: 12,
    lineHeight: 16,
  },
  strong: {
    fontFamily: 'nunito-regular, sans-serif',
    fontFamilyBold: 'nunito-semi-bold, sans-serif',
    fontSize: 20,
    lineHeight: 32,
  },
  p: {
    fontFamily: 'nunito-regular, sans-serif',
    fontFamilyBold: 'nunito-semi-bold, sans-serif',
    fontSize: 16,
    lineHeight: 24,
  },
  p1: {
    fontFamily: 'nunito-regular, sans-serif',
    fontFamilyBold: 'nunito-semi-bold, sans-serif',
    fontSize: 14,
    lineHeight: 20,
  },
  label: {
    fontFamily: 'nunito-regular, sans-serif',
    fontFamilyBold: 'nunito-semi-bold, sans-serif',
    fontSize: 12,
    lineHeight: 16,
  },
};

const breakpoints = {
  tablet: 1024,
  phone: 600,
};

const mainTheme = {
  size,
  color,
  shadow,
  animationTime,
  typography,
  gradient,
  breakpoints,
  topBar: {
    height: 80,
    heightMobile: 0,
    shadow: shadow.none,
    background: 'transparent',
  },
  widgetBar: {},
  content: {
    shadow: shadow.content,
    padding: {
      top: size.s,
      right: 0,
      left: size.l,
    },
  },
  button: {
    action: {
      padding: `${size.sm}px ${size.ml}px`,
      borderRadius: size.s,
      typography: typography.h6,
      backgroundColor: color.primary,
      color: color.grey7,
      border: 'none',
      shadow: shadow.simple,
      iconMarginRight: 0,
      width: 'auto',
      height: size.xxl,
      iconSize: size.s,
      textAlign: 'center',
      inline: false,
      hover: {
        border: 'none',
        backgroundColor: color.primary,
        shadow: shadow.simple,
        color: color.grey7,
        fill: color.grey7,
        textDecoration: 'none',
      },
      disabled: {
        backgroundColor: color.disabled,
        color: color.grey7,
        border: 'none',
      },
      active: {
        backgroundColor: color.primary,
        color: color.grey7,
        padding: `${size.s}px ${size.l}`,
        border: 'none',
        borderRadius: size.s,
        shadow: shadow.simple,
        fill: color.grey7,
        textDecoration: 'none',
      },
    },
    primary: {
      padding: `${size.sm}px ${size.ml}px`,
      borderRadius: size.s,
      typography: typography.h6,
      backgroundColor: color.green1,
      color: color.contrast,
      border: 'none',
      shadow: shadow.simple,
      iconMarginRight: 0,
      width: 'auto',
      height: size.xxl,
      iconSize: `${size.ml}px`,
      textAlign: 'center',
      inline: false,
      hover: {
        border: 'none',
        backgroundColor: color.green2,
        shadow: shadow.simple,
        color: color.contrast,
        fill: color.contrast,
        textDecoration: 'none',
      },
      disabled: {
        backgroundColor: color.grey5,
        color: color.grey3,
        border: 'none',
      },
      active: {
        backgroundColor: color.green2,
        color: color.contrast,
        padding: `${size.s}px ${size.l}`,
        border: 'none',
        borderRadius: size.s,
        shadow: shadow.simple,
        fill: color.contrast,
        textDecoration: 'none',
      },
    },
    link: {
      padding: 0,
      borderRadius: 0,
      typography: typography.h6,
      backgroundColor: 'transparent',
      color: color.green4,
      border: 'none',
      shadow: shadow.none,
      iconMarginRight: 0,
      width: 'initial',
      height: 'auto',
      iconSize: '',
      textAlign: 'left',
      inline: true,
      hover: {
        border: 'none',
        backgroundColor: 'transparent',
        shadow: shadow.none,
        color: color.green4,
        fill: color.green4,
        textDecoration: 'underline',
      },
      disabled: {
        backgroundColor: 'transparent',
        color: color.disabled,
        border: 'none',
        textDecoration: 'underline',
      },
      active: {
        backgroundColor: 'transparent',
        color: color.green4,
        padding: 0,
        border: 'none',
        borderRadius: 0,
        shadow: shadow.none,
        fill: color.green4,
        textDecoration: 'underline',
      },
    },
    nav: {
      padding: `${size.sm}px ${size.ml}px`,
      borderRadius: size.s,
      typography: typography.h6,
      backgroundColor: color.contrast,
      color: color.text,
      border: `1px solid ${color.grey5}`,
      shadow: shadow.simple,
      iconMarginRight: size.m,
      width: 'auto',
      height: size.xxl,
      iconSize: `${size.ml}px`,
      textAlign: 'center',
      inline: false,
      hover: {
        border: `1px solid ${color.grey5}`,
        backgroundColor: color.contrast,
        shadow: shadow.simple,
        color: color.text,
        fill: color.text,
        textDecoration: 'none',
      },
      disabled: {
        backgroundColor: color.contrast,
        color: color.disabled,
        border: `1px solid ${color.grey5}`,
      },
      active: {
        backgroundColor: color.contrast,
        color: color.text,
        padding: `${size.sm}px ${size.ml}px`,
        border: `1px solid ${color.grey5}`,
        borderRadius: size.s,
        shadow: shadow.simple,
        fill: color.text,
        textDecoration: 'none',
      },
    },
    page: {
      padding: 0,
      borderRadius: size.s,
      typography: typography.h7,
      backgroundColor: color.contrast,
      color: color.grey1,
      border: `1px solid transparent`,
      shadow: shadow.none,
      iconMarginRight: size.m,
      width: size.xl,
      height: size.xl,
      iconSize: `${size.ml}px`,
      textAlign: 'center',
      inline: false,
      hover: {
        border: `1px solid ${color.grey4}`,
        backgroundColor: color.contrast,
        shadow: shadow.none,
        color: color.text,
        fill: color.text,
        textDecoration: 'none',
      },
      disabled: {
        backgroundColor: color.contrast,
        color: color.disabled,
        border: `1px solid ${color.grey4}`,
      },
      active: {
        backgroundColor: color.contrast,
        color: color.text,
        padding: 0,
        border: `1px solid ${color.grey4}`,
        borderRadius: size.s,
        shadow: shadow.none,
        fill: color.text,
        textDecoration: 'none',
      },
    },
    search: {
      padding: `${size.s}px ${size.l}`,
      borderRadius: size.s,
      typography: typography.label,
      backgroundColor: color.primary,
      color: color.contrast,
      border: 'none',
      shadow: shadow.simple,
      iconMarginRight: 0,
      width: 'auto',
      height: 'auto',
      iconSize: '',
      textAlign: 'center',
      inline: true,
      hover: {
        border: 'none',
        backgroundColor: color.primary,
        shadow: shadow.simple,
        color: color.contrast,
        fill: color.contrast,
        textDecoration: 'none',
      },
      disabled: {
        backgroundColor: color.grey6,
        color: color.disabled,
        border: 'none',
      },
      active: {
        backgroundColor: color.primary,
        color: color.contrast,
        padding: `${size.s}px ${size.l}`,
        border: 'none',
        borderRadius: size.s,
        shadow: shadow.none,
        fill: color.contrast,
        textDecoration: 'none',
      },
    },
    quiet: {
      padding: '0',
      borderRadius: '0',
      typography: typography.p,
      backgroundColor: 'transparent',
      color: color.grey3,
      border: 'none',
      shadow: shadow.none,
      iconMarginRight: 10,
      width: 'auto',
      height: 'auto',
      iconSize: `${size.ml}px`,
      textAlign: 'center',
      inline: true,
      hover: {
        border: 'none',
        backgroundColor: 'transparent',
        shadow: shadow.none,
        color: color.grey3,
        fill: color.grey3,
        textDecoration: 'none',
      },
      disabled: {
        backgroundColor: 'transparent',
        color: color.disabled,
        border: `none`,
      },
      active: {
        backgroundColor: 'transparent',
        color: color.grey3,
        padding: '0',
        border: 'none',
        borderRadius: '0',
        shadow: shadow.none,
        fill: color.grey3,
        textDecoration: 'none',
      },
    },
    sidebarNav: {
      padding: `${size.m}px`,
      borderRadius: 0,
      typography: typography.p,
      backgroundColor: 'transparent',
      color: color.grey3,
      border: 'none',
      shadow: shadow.none,
      iconMarginRight: size.m,
      width: '100%',
      height: 'auto',
      iconSize: '',
      textAlign: 'left',
      inline: false,
      hover: {
        border: 'none',
        backgroundColor: 'transparent',
        shadow: shadow.none,
        color: color.grey4,
        fill: color.grey4,
        textDecoration: 'underline',
      },
      disabled: {
        backgroundColor: 'transparent',
        color: color.disabled,
        border: 'none',
      },
      active: {
        backgroundColor: 'transparent',
        color: color.grey7,
        padding: `${size.m}px`,
        border: 'none',
        borderRadius: 0,
        shadow: shadow.none,
        fill: color.secondary,
        textDecoration: 'none',
      },
    },
    fitted: {
      padding: `${size.xs}px`,
      borderRadius: 0,
      typography: typography.h3,
      backgroundColor: 'transparent',
      color: color.contrast,
      border: 'none',
      shadow: shadow.none,
      iconMarginRight: 0,
      width: 'fit-content',
      height: 'fit-content',
      iconSize: '',
      textAlign: 'left',
      inline: true,
      hover: {
        border: 'none',
        backgroundColor: 'transparent',
        shadow: shadow.none,
        color: color.green2,
        fill: color.green2,
        textDecoration: 'none',
      },
      disabled: {
        backgroundColor: 'transparent',
        color: color.disabled,
        border: 'none',
      },
      active: {
        backgroundColor: `transparent`,
        color: color.green1,
        padding: `${size.xs}px`,
        border: 'none',
        borderRadius: 0,
        shadow: shadow.none,
        fill: color.green1,
        textDecoration: 'none',
      },
    },
    actionLight: {
      padding: `${size.s}px`,
      borderRadius: `${size.s}px`,
      typography: typography.h8,
      backgroundColor: 'transparent',
      color: color.grey1,
      border: `1px solid ${color.grey5}`,
      shadow: shadow.none,
      iconMarginRight: 10,
      width: 'fit-content',
      height: 'fit-content',
      iconSize: `${size.sm}px`,
      textAlign: 'left',
      inline: true,
      hover: {
        border: `1px solid ${color.green1}`,
        backgroundColor: 'transparent',
        shadow: shadow.none,
        color: color.grey1,
        fill: color.green1,
        textDecoration: 'none',
      },
      disabled: {
        backgroundColor: 'transparent',
        color: color.disabled,
        border: `1px solid ${color.disabled}`,
      },
      active: {
        backgroundColor: `transparent`,
        color: color.grey1,
        padding: `${size.s}px`,
        border: `1px solid ${color.green1}`,
        borderRadius: 8,
        shadow: shadow.none,
        fill: color.green1,
        textDecoration: 'none',
      },
    },
  },
  input: {
    typography: typography.p1,
    padding: size.s,
    border: `1px solid ${color.grey5}`,
    borderRadius: size.s,
    color: color.text,
    hover: {
      backgroundColor: color.contrast,
    },
    active: {
      border: `1px solid ${color.green1}`,
    },
    error: {
      backgroundColor: color.errorContrast,
      border: `1px solid ${color.error}`,
    },
    password: {
      paddingRight: size.xl,
    },
  },
  inputWrapper: {
    hover: {
      fill: color.grey2,
    },
    focus: {
      fill: color.grey2,
    },
    error: {
      fill: color.errorContrast,
    },
  },
  floatingLabel: {
    color: color.grey2,
    typography: typography.p1,
    focus: {
      color: color.grey2,
      typography: typography.p1,
    },
    error: {
      color: color.error,
    },
  },
  list: {
    iconList: {
      padding: size.ml,
      backgroundColor: color.grey6,
      li: {
        height: 'auto',
        paddingLeft: 0,
        marginBottom: 8,
        border: 'none',
        cursor: 'default',
        alignItems: 'flex-start',
      },
    },
    buttonList: {
      padding: '0',
      backgroundColor: color.primary,
      li: {
        height: 'auto',
        paddingLeft: size.ml,
        marginBottom: size.m,
        border: `1px solid ${color.primary}`,
        cursor: 'pointer',
        alignItems: 'center',
      },
    },
  },
  checkbox: {
    width: size.ml,
    height: size.ml,
    padding: 4,
    border: `1px solid ${color.primary}`,
    borderRadius: 3,
    hover: {
      backgroundColor: color.grey6,
      shadow: shadow.simple,
    },
    active: {
      backgroundColor: color.grey6,
      border: `1px solid ${color.primary}`,
      shadow: shadow.simple,
    },
    error: {
      backgroundColor: color.errorContrast,
      border: `1px solid ${color.error}`,
    },
  },
  radio: {
    width: size.ml,
    height: size.ml,
    padding: 4,
    border: `1px solid ${color.primary}`,
    hover: {
      backgroundColor: color.grey6,
      shadow: shadow.simple,
    },
    active: {
      backgroundColor: color.grey6,
      border: `1px solid ${color.primary}`,
      shadow: shadow.simple,
    },
    checked: {
      backgroundColor: color.primary,
    },
  },
  container: {
    margin: 40,
    marginMobile: 20,
  },
  notification: {
    SUCCESS: {
      backgroundColor: color.secondary,
      color: color.contrast,
      borderColor: color.secondary,
    },
    INFO: {
      backgroundColor: color.contrast,
      color: color.grey1,
      borderColor: color.green1,
    },
    ERROR: {
      backgroundColor: color.error,
      color: color.contrast,
      borderColor: color.error,
    },
  },
};

export default mainTheme;
